config/routes.rb
Crowdcode::Application.routes.draw do
  root :to => "static_pages#index"  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :categories, only: [:index, :show]
  resources :tutorials
  resources :tags, only: [:index, :show]
  resources :comments do 
    resources :comments 
  end
  resources :votes, 
            :only => [:create, :update]  

  resources :bookmarks, only: [:create, :destroy]
  
  match '/about', to: "static_pages#about"
  match 'profile', :to => 'users#profile', :as => :user_root, via: :get
  match '/:username', :to => 'users#profile', :as => :public_profile, via: :get

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :description
  # after_create :send_welcome_email
  has_many :tutorials, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  validates_uniqueness_of :username
  def voted?(votable)
    get_vote(votable).present?
  end

  def get_vote(votable)
    self.votes.where(votable_id: votable.id, :votable_type => votable.class.to_s).first
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  # def send_welcome_email
  #   UserMailer.welcome_email(self).deliver
  # # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
   active_user = params[:username] || current_user.username
   @user =  User.includes(:tutorials, 
    											:comments, 
                          :votes, 
                          :bookmarks).find_by_username(active_user)
  end

  def show
    @user = User.includes(:tutorials).find_by_username(params[:username])
  end
end

app/views/users/profile.html.erb
<div class="profile-container">
<span id="profile-pic"><%= gravatar_for(@user.email) %></span><br>
<div class="top-bar-profile">
<h1 id="user-info"><%= @user.username.capitalize %>
</h1>
<small><%= link_to "Edit", edit_user_registration_path %></small>
<small>Last signed in <%= (time_ago_in_words(@user.last_sign_in_at)) %> ago</small>
<br>
</div>
<div class="user-description">
<%= @user.description %>
</div>
<ul class="tabs">
	<li class="active"><a href="#tab1">Summary</a></li>
	<li><a href="#tab2">Tutorials</a></li>
	<li><a href="#tab3">Comments</a></li>
	<li><a href="#tab4">Votes</a></li>
	<li><a href="#tab5">Bookmarks</a></li>
</ul>

<div class="stats">
	<div class="tutorials">
		<div class="tab" id="tab1">
			<h2>You have submitted <%= @user.tutorials.count%> <%= link_to  'tutorials',new_tutorial_path %></h2>
			<li>You have made <%= @user.comments.count %> insightful <%= link_to 'comments', tutorial_path(rand(1..5)) %></li>
			<li>You have cast <%= @user.votes.count %> <%= link_to 'votes', tutorials_path%></li>
		</div>

	
			<div class="tab" id ="tab2">
			<% if @user.tutorials.count == 0 %>
				<h2>no tutorials yet</h2>
				<% else %>
				<h2>Tutorials</h2>
				<% @user.tutorials.each do |tut| %>
						<li><%= link_to tut.title, generate_url(tut) %></li>
				<% end %>
			<% end %>
		</div>


		<div class="tab" id ="tab3">
			<% if @user.comments.count == 0 %>
				<h2>No comments yet.</h2>
				<% else %>
				<h2>Latest Comments</h2>
				<% @user.comments.limit(5).each do |comment| %>
						<li>
					  <%= link_to comment.content, comment.commentable_type.constantize.find(comment.commentable_id) %> 
					  <small><%= time_ago_in_words(comment.created_at)%> ago</small> 
				  </li>
				<% end %>
			<% end %>
		</div>

		<div class="tab" id ="tab4">
				<% if @user.votes.count == 0 %>
					<h2>No votes yet.</h2>
					<% else %>
					<h2>Latest Votes</h2>
					<% @user.votes.limit(5).each do |vote| %>
							<li>
						 <%= link_to vote.votable_type.constantize.find(vote.votable_id).title, vote.votable_type.constantize.find(vote.votable_id) %>
				  	<small><%= time_ago_in_words(vote.created_at) %> ago</small>
					  </li>
					<% end %>
				<% end %>
			</div>

		  <div class="tab" id="tab5">
		  	<% if @user.bookmarks.count == 0 %>
		  		<h2>No bookmarks yet.</h2>
		  	<% else %>
		  	  <% @user.bookmarks.limit(5).each do |bookmark| %>
		  	    <li>
	  	  	  <%= link_to bookmark.tutorial.title, bookmark.tutorial %>
	  	    </li>
	  	    <small><%= time_ago_in_words(bookmark.created_at)%> ago</small> 
	  	  <% end %>
	  </div>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <span id="profile-pic"><%= gravatar_for(@user.email) %></span>
  <div class="top-bar-profile">
    <h1 id="user-info"><%= @user.username.capitalize %>'s profile</h1>
  </div>
  <div class="users-tutorials">
    <h3><%= @user.username.capitalize %>'s Recent Tutorials</h3>
    <div class="tutorials profile-tuts">
      <% @user.tutorials.each do |tut| %>
        <%= render 'shared/tutorial_box', tut: tut %>
      <% end %>
    </div>
  </div>
</div>