config/routes.rb
Crowdcode::Application.routes.draw do
  root :to => "static_pages#index"  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :categories, only: [:index, :show]
  resources :tutorials
  resources :tags, only: [:index, :show]
  resources :comments do 
    resources :comments 
  end
  resources :votes, 
            :only => [:create, :update]  

  resources :bookmarks, only: [:create, :destroy]
  
  match '/about', to: "static_pages#about"
  match 'profile', :to => 'users#profile', :as => :user_root, via: :get
  match '/:username', :to => 'users#profile', :as => :public_profile, via: :get

  

  

end

app/views/shared/_addthis.html.erb
<div class="add-this" id="social-buttons">
  <div addthis:title="<%= tut.title%>" addthis:description="Check out this tutorial on crowdco.de" addthis:url="http://crowdco.de/tutorials/<%= tut.id %>" class="addthis_toolbox addthis_default_style">
    <a class="addthis_button_twitter"></a>
    <a class="addthis_button_facebook"></a>
    <a class="addthis_button_google_plusone_share" style="cursor:pointer"></a>
    <a class="addthis_button_stumbleupon"></a>
    <a class="addthis_button_reddit"></a>
    <a class="addthis_button_email"></a>
  </div>
</div>

app/views/shared/_addthis_toolbox.html.erb
 <div class="addthis_toolbox addthis_floating_style addthis_32x32_style">
  <a class="addthis_button_twitter"></a>
  <a class="addthis_button_facebook"></a>
  <a class="addthis_button_google_plusone_share"></a>
  <a class="addthis_button_stumbleupon"></a>
  <a class="addthis_button_reddit"></a>
  <a class="addthis_button_email"></a>
</div>

app/views/shared/_comment.html.erb
<li id="<%= comment.id %>">
  <a name="comment<%=comment.id%>"></a>
  <%= gravatar_for comment.user.email, size: 40 %>
  <%= link_to comment.user.username.capitalize , comment.user.username, class: "username"  %>
  <small>
  <%= time_ago_in_words(comment.created_at) %> ago
  <% if current_user && comment.author?(current_user) || current_user && current_user.admin? %>
    <%= link_to "Delete", comment_path(comment), method: :delete %>
    <%= link_to "Edit", edit_comment_path(comment) %>
  <% end %>
    <%= link_to "Reply", "#", class: "reply" %>
    <%= link_to "#", "#comment#{comment.id}" %>
  </small>
  <p class="main"><%= comment.content %></p>
  <section id="nested-comments">
    <%= render 'comments/nested_comments', comment: comment %>
  </section>
  <%= render 'comments/nested_comment_form', comment: comment %>
</li>

app/views/shared/_comments.html.erb
<section id="comment-list">
  <div class="comment-stats">
   <%= render 'comments/comment_count', tutorial: tutorial %>
  </div>
  <ul>
  <% @comments.each do |comment| %>
     <%= render 'shared/comment', comment: comment %>
  <% end %>
  </ul>
</section>

app/views/shared/_comments_form.html.erb
<%= form_for @comment, id: "comment-form", :remote => true do |f| %>
<%= f.hidden_field :commentable_id %>
<%= f.hidden_field :commentable_type %>
<%= f.text_area :content, size: "30x5", placeholder: "Add comment here" %><br>
<%= f.submit "Add comment", class: "btn btn-primary" %>
<% end %>
<a name="comment-form"></a> 

app/views/shared/_create_bookmark.html.erb
  <%= button_to "favorite", { action: "create", controller: "bookmarks", id: tutorial.id }, remote: true %>

app/views/shared/_delete_bookmark.html.erb
	<%= button_to "unfavorite", { action: "destroy", controller: "bookmarks", id: tutorial.id }, method: :delete, remote: true %>  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
  	<% object.errors.full_messages.each do |msg| %>
  	  <li>*<%= msg %></li>
  	<% end %>
  </ul>
<% end %>

app/views/shared/_meta_info.html.erb
<div class="meta-info">
  <div class="votes">
    <span class="icon votes"><%= tut.vote_count ? tut.vote_count : "0" %>  </span>
    <div class="vote-btns">
      <% if user_signed_in? && !tut.author?(current_user) %>
        <% voted = current_user.voted?(tut) ? true : false %>
        <%= render 'votes/vote', :votable_type => tut, :voted => voted %>
      <% elsif current_user && current_user.admin? %>
        <%= render 'votes/vote', votable_type: tut, voted: false %>
      <% else %>
        <%= render 'votes/vote', :votable_type => tut, :voted => voted %>
      <% end %>
    </div>
  </div>
  <div class="favorite">
    <% if current_user && !tut.bookmarked_by?(current_user) %>
      <span class="icon star"><i class="ss-icon">star</i></span>
    <% elsif current_user %>
      <span class="icon star-yellow"><i class="ss-icon">star</i></span>
    <% else %>
      <span class="icon star"><i class="ss-icon">star</i></span>
    <% end %>
  </div>
  <span class="icon comments"><a href="/tutorials/<%= tut.id %>#comment-list"><i class="ss-icon">chat</i></a><span class="comment-count"><%= tut.comments.count %></span></span>
</div>

app/views/shared/_mobile_footer.html.erb
<div class="fixed-menu visible-phone">
  <div class="box box1">
    <i class="ss-icon"><a href="/">home</a></i>
  </div>

  <div class="box box2">
    <i class="ss-icon"><a href="#" id="list-menu">list</a></i>
  </div>

  <div class="menu-categories" style="display:none;">
    <h5>Categories</h5>
    <hr>
    <% @categories.each do |category| %>
      <p><a href="/categories/<%= category.id%>"><%= category.name %></a></p>
    <% end %>
  </div>

  <div class="box box3">
    <i class="ss-icon"><a class="last-box" href="#">action</a></i>
  </div>
  <div class="menu-share-links" style="display:none;">
  <%= render 'shared/addthis_toolbox', tut: @tutorial %>
  </div>
</div>

app/views/shared/_ribbon.html.erb
<div class="ribbon-wrapper-green"><div class="ribbon-green">Featured!</div></div>

app/views/shared/_tutorial_box.html.erb
<div class="tutorial-box" id="<%= tut.id %>">
  <% if tut.url.blank?  %>
    <%= render 'shared/ribbon' %>
  <% end %>
  <div class="tutorial-content">
    <%= link_to image_tag( tut.category.img, class: "tutorial-img"),  generate_url(tut) %>
    <div class="tutorial-text">
      <%= render 'shared/tutorial_category_link', tut: tut %><br>
    <% if tut.url.blank? %>
      <%= link_to tut.title, generate_url(tut) , { class: "tutorial-title" } %>
    <% else %>
      <%= link_to tut.title, generate_url(tut) , { class: "tutorial-title", target: '_blank' } %>
    <% end %>
    <%= render 'shared/meta_info', tut: tut %>
    <%= render 'shared/addthis', tut: tut %>
    </div>
  </div>
</div>

app/views/shared/_tutorial_category_link.html.erb
<%= link_to tut.category.name, tut.category, {class: "category-link"} %>

app/views/shared/_vote_module.html.erb
<div class="votes">
  <span class="points"><%= tut.vote_count ? tut.vote_count : "0" %> </span> Points
  <div class="vote-btns">
    <% if user_signed_in? && !tut.author?(current_user) %>
      <% voted = current_user.voted?(tut) ? true : false %>
      <%= render 'votes/vote', :votable_type => tut, :voted => voted %>
    <% end %>
  </div>
</div>