config/routes.rb
Crowdcode::Application.routes.draw do
  root :to => "static_pages#index"  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :categories, only: [:index, :show]
  resources :tutorials
  resources :tags, only: [:index, :show]
  resources :comments do 
    resources :comments 
  end
  resources :votes, 
            :only => [:create, :update]  

  resources :bookmarks, only: [:create, :destroy]
  
  match '/about', to: "static_pages#about"
  match 'profile', :to => 'users#profile', :as => :user_root, via: :get
  match '/:username', :to => 'users#profile', :as => :public_profile, via: :get

  

  

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :tags_attributes, :category_id, :url

  belongs_to :user
  has_many :tags, through: :taggings
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  belongs_to :category
  has_many :bookmarks, dependent: :destroy
  before_save :clean_tutorial_url

  VALID_URL_REGEX = /^(http|https):\/\/|[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/ix
  validates :content, presence: true, length: { minimum: 100 }, if: :url?
  validates :url, presence: true, format: { with: VALID_URL_REGEX }, if: :content?
  validates :title, presence: true, length: { minimum: 4 } 
  validates :user_id, presence: true, numericality: true

  default_scope order("popularity desc")

  def create_tags(tags)
  	tags = tags.split(" ")
  	tags.each do |tag|
  		tag = Tag.find_or_create_by_content(tag)
  		Tagging.create(taggable_id: self.id, taggable_type: "Tutorial", tag_id: tag.id)
  	end
  end

  def author?(user)
    self.user == user
  end
  
  def vote_count
    self.votes.map(&:score).inject(:+)
  end


  def self.update_popularity
    Tutorial.all.each do |tut|
      tut.popularity = tut.votes.count/(((Time.now - tut.created_at)/3600.0)**1.5)
      tut.save
    end
  end

  def content?
    content.blank?
  end

  def url?
    url.blank?
  end

  def bookmarked_by?(user)
    Bookmark.find_by_user_id_and_tutorial_id(user.id, self.id)
  end

  def clean_tutorial_url
    if self.url.present?
      self.url = self.url.gsub("http://", "")
    end
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

	before_filter :authenticate_user!, only: [:new, :create]

	def new 
		@tutorial = Tutorial.new
	end

	def edit
		@tutorial = Tutorial.find(params[:id])
		get_tags_string(@tutorial)
	end

	def index
		@search = Tutorial.search(params[:q])
		@tutorials = @search.result	
	end

	def update
		@tutorial = Tutorial.find(params[:id])
		if @tutorial.update_attributes(params[:tutorial])
			@tutorial.tags.clear
			@tutorial.create_tags(params[:tag])
			redirect_to @tutorial, notice: "Update successful!"
		else
			debugger
      redirect_to :back, notice: "Something went wrong"
    end
	end


	def destroy
		@tutorial = Tutorial.find(params[:id]).destroy
		redirect_to '/profile'
	end

	
	def create 
		p params[:tutorial]
		puts '*' * 400
		@tutorial = Tutorial.new(params[:tutorial])
		@tutorial.user_id = current_user.id
		if @tutorial.save 
		  @tutorial.create_tags(params[:tag])
			redirect_to @tutorial, notice: "Thanks for creating a tutorial"
		else
			render :new
		end
	end

	def show 
		@tutorial = Tutorial.includes(:category).find(params[:id])
		@markdown = MARKDOWN.render(@tutorial.content) if @tutorial.content
		@tags = @tutorial.tags
    @comments = @tutorial.comments.includes(:user)
    @comment = @tutorial.comments.new
	end


	
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
	def generate_url(tutorial)
		if tutorial.url.blank? 
			tutorial
		else
			"http://#{tutorial.url}"
		end
	end
end

app/views/tutorials/_bookmark.html.erb
<% if current_user && !tutorial.bookmarked_by?(current_user) %>
	<%= render 'shared/create_bookmark', tutorial: tutorial %>
<% else %>
	<%= render 'shared/delete_bookmark', tutorial: tutorial %>
<% end %>

app/views/tutorials/_tutorials.html.erb
<% tutorials.each do |tut| %>
    <%= render 'shared/tutorial_box', tut: tut %>
<% end %>

app/views/tutorials/edit.html.erb
<div class="tutorial-form">
  <h2>Edit your tutorial</h2>

  <%= form_for @tutorial do |f| %>
    <%= render 'shared/error_messages', object: @tutorial %>
    <%= f.label "Choose Category:" %>
    <%= collection_select(:tutorial, :category_id, Category.all, :id, :name) %>
    <%= f.label :title %>
    <%= f.text_field :title, value: @tutorial.title %>
   
    <% if @tutorial.content.blank? %>
      <%= f.label :url %>
      <%= f.text_field :url, value: @tutorial.url %>
    <% else %>
      <%= f.label :content %>
      <%= f.cktext_area :content, value: @tutorial.content %>
    <% end %>
    <%= label_tag :tags %>
    <%= text_field_tag :tag, @tags %>
    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/tutorials/index.html.erb
<%= render 'shared/search' %>
<div class="tutorial-list">
	<%= render 'tutorials/tutorials', tutorials: @tutorials %>
</div>

app/views/tutorials/index.js.erb
$('div.tutorial-list').html("<%= j render 'tutorials/tutorials', tutorials: @tutorials %>");

app/views/tutorials/new.html.erb
<div class="tutorial-form">
  <%= form_for @tutorial do |f| %>
  <h2>Create a tutorial</h2>
    <%= render 'shared/error_messages', object: @tutorial %>
    <%= f.label "Choose Category:" %>
    <%= collection_select(:tutorial, :category_id, Category.all, :id, :name) %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= label_tag :tutorial_type %>
    <div class="tutorial-radio-btns">
      <div class="create-tutorial-radio">
        <%= radio_button_tag(:tut_type, checked = true, "create tutorial") %>
        <%= label_tag(:create_tutorial, "Write a tutorial") %>
      </div>
      <div class="add-link-radio">
        <%= radio_button_tag(:tut_type, "add link") %>
        <%= label_tag(:add_link, "Add my own link")  %>
      </div>
    </div>

    <div class="tutorial_url">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    <div class="ckeditor">
      <%= f.label :content %>
      <%= f.cktext_area :content %>
    </div>


    <%= label_tag :tags %>
    <%= text_field_tag :tag, nil, placeholder: "e.g. ruby ruby-on-rails javascript oauth" %>
    <%= f.submit "Submit tutorial", class: "btn btn-success" %>   
  <% end %>
</div>

app/views/tutorials/new.js.erb
	<% if @tutorial.errors.full_messages.include?("Url is invalid") %>
		<% debugger %>
	  $('input#tutorial_url').show();
	 	$('div.ckeditor').hide();
	<% end %>

app/views/tutorials/search.html.erb
<%= form_for @search do |f| %>
<%= f.text_field "hello" %>
<%= f.submit %>
<% end %>

app/views/tutorials/show.html.erb
<%= content_for :highlight_script do  %>
  <!-- The below scripts and js are here because I do not want to load them on any other pages -->
  <%= javascript_include_tag "highlightjs" %>
  <!-- Sets theme syntax highlighting in code blocks -->
  <!-- <link rel="stylesheet" href="/stylesheets/tomorrow-night.css"> -->
  <!-- highlight js for syntax highlighting -->
  <script src="/javascripts/highlight.pack.js"></script>
<% end %>

<div class="tutorial-show" id="<%= @tutorial.id %>">
   <% if @tutorial.url.blank?  %>
    <%= render 'shared/ribbon' %>
  <% end %>
  <div class="tutorial-title">
    <h1><%= @tutorial.title %></h1>
  </div>
  <div class="meta-tut-show">
    <%= render 'shared/meta_info', tut: @tutorial %>
  </div>
  <div class="date-and-time">
    <div class="created-by">
      <p>By: <a href="/<%= @tutorial.user.username %>"><%=  "#{@tutorial.user.username.capitalize}"%></a> on <%= @tutorial.created_at.strftime("%B #{@tutorial.created_at.day.ordinalize}, %Y") %></p>
    </div>
    <% if @tutorial.author?(current_user) || (current_user && current_user.admin?) %>
      <div class="edit-delete">
        <%= link_to "edit", edit_tutorial_path(@tutorial) %>
        <%= link_to "delete", tutorial_path(@tutorial), method: :delete %>
      </div>
    <% end %>
  </div>
  <% if @tutorial.url.present? %>
    <%= link_to "http://www.#{@tutorial.url}", generate_url(@tutorial), class: "tutorial" %>
  <% else %>
    <%= @markdown.html_safe  %>
  <% end %>
  <hr />
    <% unless @tags.blank? %>
    <p>Tags:<% @tags.each do |tag| %>
            <%= link_to tag.content.capitalize, tag %>
            <% end %>
    </p>
  <% end %>
  <div class="comments-container">
    <%= render 'shared/comments', tutorial: @tutorial %>
    <%= render 'shared/comments_form', comment: @comment %>
  </div>

  <div class="sidebar  hidden-phone">
     <%= render 'shared/addthis_toolbox' %>
  </div>
</div>