config/routes.rb
Crowdcode::Application.routes.draw do
  root :to => "static_pages#index"  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :categories, only: [:index, :show]
  resources :tutorials
  resources :tags, only: [:index, :show]
  resources :comments do 
    resources :comments 
  end
  resources :votes, 
            :only => [:create, :update]  

  resources :bookmarks, only: [:create, :destroy]
  
  match '/about', to: "static_pages#about"
  match 'profile', :to => 'users#profile', :as => :user_root, via: :get
  match '/:username', :to => 'users#profile', :as => :public_profile, via: :get

  

  

end

app/views/layouts/_nav.html.erb
<header class="navbar ">
	<div class="navbar-inner">
		<a class="brand" href="/">Crowdcode</a>
		<nav>
			<ul class="nav pull-left visible-desktop">
				<li><%= link_to "Popular", root_path %></li>
				<li><%= link_to "All", tutorials_path %></li>
				<li id="fat-menu" class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					  Categories<b class="caret"></b>
					</a>
	        <ul class="dropdown-menu">
		        <% Category.all.each do |category| %>
			        <li><%=link_to category.name, category, class: "dropdown" %></li>
					  <% end %>
				  </ul>
				  <li><%= link_to 'Tags', tags_path %></li>
				</ul>
				
				<% if current_user  %>
				  <div class="add-tut-btn pull-left visible-desktop">
				 		<%= button_to "Add Tutorial!",new_tutorial_path, class: "btn btn-success", method: :get %>
				  </div>
				<% end %>

				 <% if current_user  %>
				 	<ul class="nav pull-right">
				    <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
				    <li><%= link_to "Profile", '/profile' %></li>
				  </ul>
				<% else %>
					<ul class="nav pull-right">
				      <li><%= link_to "Sign up", new_user_registration_path %></li>
				      <li><%= link_to "Log In", new_user_session_path %></li>
				   </ul>
				<% end %>
		</nav>
  </div>
</header>

app/views/layouts/_vote.html.erb
<ul>
  <li class="create"><%= vote_button "create", "Upvote", votable_type %></li>
  <li class="create"><%= vote_button "create", "Downvote", votable_type %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdcode</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- CSS for icons -->
  <link href="/webfonts/ss-pika.css" media="all" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- JS for ckeditor -->
  <script src="/ckeditor/ckeditor.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
  <%= yield :highlight_script %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
     <% end %>
    <%= yield %>
  </div>
  <%= render '/shared/mobile_footer', categories: @categories %>
  <!-- JS for addthis widget -->
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5169ce054b6dae19"></script>
</body>
</html>